### PR TITLE
fix: added GeometryCollection to GeoJSONUtils

### PR DESCRIPTION
**Pull request by KiwiKilian**
- Added `fromGeometryCollection`, as `GeometryCollection` is a valid `geometry` too
- Improved some `null` checks

Noticed these during reviewing #555

### CODE REVIEW

**Comment by KiwiKilian** [comment]
@jimmyasyraf could you have a look at these changes too?

**Review by jimmyasyraf — APPROVED** [review]
LGTM!

**Comment by brentforder** [comment]
Hmm can someone briefly explain the implications? Does this enable the use of GeometryCollection as a data source for ShapeSource?

**Comment by KiwiKilian** [comment]
> Does this enable the use of GeometryCollection as a data source for ShapeSource?

This was always possible.

I just wanted the interface to be type complete, as it pretended to be able to unwrap every `Feature`. The use for `Multi*` geometries was fixed in #555 and as `GeometryCollection` can also be used within a `Feature`, this should also be supported to omit a possible bug.

**Pull request merged**
