### PR TITLE
feat: unify `MapView`s `styleURL` and `styleJSON` to `mapStyle`

### LINKED ISSUE #512: RFC: Deprecate/Remove `Style` component and unify `MapView`s prop `styleURL` and `styleJSON`
Working through the examples, I noticed for the first time the [`Style` component](https://github.com/maplibre/maplibre-react-native/blob/main/javascript/components/Style.tsx). The component basically allows to read a `style.json` and it will create `Source` and `Layer` components, to render the style partially.

This is confusing, because it's also possible to pass a JSON style via `styleJSON` on `MapView`, so this functionality is duplicated. It turns out, initially there was no support for local JSON styles at all. Then the `Style` component was [introduced](https://github.com/rnmapbox/maps/issues/846), before finally `MapView` got support for also `styleJSON`. The author of both did also recommend to keep only the [functionality on `MapView` through `styleJSON`](https://github.com/rnmapbox/maps/pull/1102#issuecomment-735968413), but that component seemed to got forgotten.

I would like to do the following:

- Deprecate/Remove `Style` component
  - Removes duplicate funcitonality and confusion about which to use
  - If someone wants to render a style, but not as the `MapView` `styleJSON`, this is a user space concern, nothing this library has to solve
  - It will help keep us this library clean in functionality
- Unify `styleURL` and `styleJSON` to a new prop `mapStyle`, just like [`react-map-gl` uses](https://visgl.github.io/react-map-gl/docs/api-reference/map#mapstyle), `mapStyle` should then accept either a URL or a Style object

Smoothest migration would be first to deprecate `Style` and `MapView`s `styleURL` and `styleJSON` for one major version and then drop on the next major version. Immediate removal would be less work.

### PR DESCRIPTION
**Pull request by KiwiKilian**
Fixes #512

Migration docs on separate PR.

### CODE REVIEW

**Review by tyrauber — APPROVED** [review]
LGTM. How about adding some success and failure tests to indicate the api change?

**Comment by KiwiKilian** [comment]
How do you mein "success" and "failure" tests?

I probably should be adding tests for the `mapStyle` prop, right. But I'm not sure what you mean by success and failure.

**Comment by tyrauber** [comment]
Sorry, because of the api change, writing two tests, a success case that shows how to properly use the new prop, and a failure case that ensures that using the old prop fails in the expected way, and hopefully gracefully.    I know our test suite is severely lacking ATM though.  We can merge this in and address test coverage in another branch at a later date.

**Comment by KiwiKilian** [comment]
Passing the one of the old props will simply do nothing. If one uses TypeScript there will be a linting error.

**Pull request merged**
