### PR TITLE
feat: update maplibre native version

### LINKED ISSUE #34: Maplibre is not FOSS, Cannot publish app to F-droid
Hi !
I just recently wanted to publish [my app](https://github.com/meypod/al-azan) on f-droid,
[and we are facing some difficulties](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12697#note_1302177413)

can you help resolve these issues ?

I believe one of the reasons people would want to choose this package is to be FOSS and publish to f-droid

### PR DESCRIPTION
**Pull request by sarahsporck**
## Description

Fixes #34 

Updated maplibre-native for android so the resulting build should be FOSS again.

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [x] I have run tests via `yarn test` in the root folder
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [x] I added/updated a sample (`/example`)

### CODE REVIEW

**Comment by tyrauber** [comment]
Actually, while this resolves the Android crash, now iOS fails to build. 

> AppDevelopment.xcodeproj: error: Missing package product 'Mapbox' (in target 'AppDevelopment' from project 'AppDevelopment')

**Comment by tyrauber** [comment]
Oooff, breaking changes in 6.0.0 for iOS:
https://github.com/maplibre/maplibre-gl-native-distribution

```
💥 Breaking: Changed the prefix of files, classes, methods, variables and everything from MGL to MLN. (https://github.com/maplibre/maplibre-native/pull/919).

To migrate:
Change all your MGL prefixes to MLN. If you are using NSKeyedArchiver or similar mechanishm to save the state, the app may crash after this change when trying to unarchive the state using old names of the classes. You need to clean the saved state of the app and save it using new classes.

The Swift package needs to be imported with import MapLibre instead of import Mapbox.
```

**Comment by tyrauber** [comment]
Sorry @sarahsporck, false alarm.  This builds and runs on iOS as well.  Pulled and rebased off of main as of #[27ec4c6](https://github.com/maplibre/maplibre-react-native/commit/27ec4c6dff18bca03aba8bdc9633a41f6756fda9) here [c2d4850](https://github.com/tyrauber/maplibre-react-native/commit/c2d4850fcdcf6ea67731f3482c08396d487ac3fc).  Tested in simulators and devices. Just rebase off main and this is good to go!  Nice work!

**Comment by meypod** [comment]
@tyrauber maplibre is still not usable on f-droid due to using `https://dl.bintray.com/maplibre/maplibre-gl-native` maven repo

**Comment by meypod** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15592

**Pull request merged**
