### PR TITLE
fix link in Camera doc

### LINKED ISSUE #32: Camera followUserMode example link broken
Hello, the example link in the documentation for "followUserMode" in the Camera section is broken. Could this be removed or fixed?

### PR DESCRIPTION
**Pull request by jthiard**
## Description

Fixes #32

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [x] I updated the documentation with running `yarn generate` in the root folder
- [x] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/updated a sample (`/example`)

### CODE REVIEW

**Comment by ianthetechie** [comment]
Sorry I missed this earlier @jthiard. Could you fix the changelog conflict (or even just remove that? I'm not sure if we need a changelog entry for small things like this).

**Comment by jthiard** [comment]
Hi @ianthetechie
Sure, give me a couple hours and I'll fix the conflict

**Comment by ianthetechie** [comment]
Perfect. Thanks! I'll keep an eye out and can push a release with this as well as #29 later today :)

**Comment by jthiard** [comment]
@ianthetechie I updated the PR to fix the conflict, as you suggested I just removed my entry in the changelog, I'm ok to skip small fixes like this.

**Pull request merged**
