### PR TITLE
Fix/build and test plugin

### LINKED ISSUE #16: Fix plugin build
Running `yarn build:plugin` currently doesn't work. I'm not sure if we forked in a broken state or if I ended up breaking something while attempting to modernize the project and rip out mapbox. This will block #2.

### PR DESCRIPTION
**Pull request by jthiard**
## Description

May fixes #16 

- Fix `yarn build:plugin` by upgrading yarn to 3.3.1 (see yarnpkg/berry#5127)
- Fix `yarn test:plugin` by squeezing `expo-modules` (which are just some shell scripts using npx, and don't work in pnp) and directly calling jest.

I'm not using Expo in my projects so I'm not sure everything is ok in the built plugin but will get a try. At least the commands are working now.

### CODE REVIEW

**Comment by ianthetechie** [comment]
Hey, thanks a bunch!  I still ran into one issue when running locally. `tsc` complained that it couldn't import a bunch of stuff which all comes from `@types/node`, so I installed that and it worked.

I can't seem to actually commit to this branch (GitHub forks are a bit different I guess), so I'll just merge this as-is and make some edits on `master`.

Apparently we also need to figure out now why `build:plugin` and `test:plugin` don't show up *anywhere* else; not even CI... 🤔 Maybe these are no longer used? I don't know enough about expo either but it looks like this might not even be a blocker to a release.

**Comment by jthiard** [comment]
Hi, thanks for merging !
I saw the last CI fail after this merge in android examples, I and think I accidentally introduced a bug in the example yarn config https://github.com/maplibre/maplibre-react-native/pull/17/files#diff-b0ffbd64d2ca4a353162daee526a8f8897f945e4588d5d4877eee42f0c21ba81R3

Should be

```
yarnPath: ../.yarn/releases/yarn-3.3.1.cjs
```

I can't push a new PR until tomorrow.

**Comment by ianthetechie** [comment]
Yup yup ;)

**Comment by ianthetechie** [comment]
No worries; I'll take care of it.

**Pull request merged**
