### PR TITLE
Js to ts

### LINKED ISSUE #4: Migrate from JS to TS
RN appears to use a method of runtime type check enforcement, which is essentially deprecated and becomes unnecessary when using TypeScript. See https://github.com/facebook/react-native/issues/33557 for context.

This should ultimately enable us to remove both the duplicated peer+dev dependency on `prop-types` (to get unit tests passing) and let us ditch `deprecated-react-native-prop-types`, which FB added as a stop gap for JS projects and I presume is very much deprecated ;)

### PR DESCRIPTION
**Pull request by sarahsporck**
## Description

Fixes #4 

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [x] I have run tests via `yarn test` in the root folder
- [x] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] ~~I updated the typings files (`index.d.ts`)~~
- [ ] I added/updated a sample (`/example`)

---

I took quite a bit of inspiration from the https://github.com/rnmapbox/maps repo, as they already "finished" their ts migration a while ago.

### CODE REVIEW

**Comment by tyrauber** [comment]
@sarahsporck This is awesome! Once the snapshots are updated `yarn test -- -u` the tests pass.   There are a lot of changes here. What needs to happen in this branch before it can be merged?  Are you hoping to resolve the ~130 outstanding lint issues? Would you like some help?

**Comment by sarahsporck** [comment]
So the snapshot tests are updated. regarding the linting issues. I tried not to change to much existing code. And it seems there are at least more than a 100 linting warnings on the main branch already. As this pr is already quite unbearably large I'd tackle them in a separate pr on top of this one :) 

Regarding reviewing. I think it makes sense to do more of a functional review, as doing a full fledged code review would eat a lot of time and resources. Although there are a few files where I did struggle a bit during refactoring, which would be the `MapView` and `Camera`, as they both contain a lot of code, as well as the animated stuff, as it was not well documented. Maybe you could focus on that :)

**Comment by tyrauber** [comment]
Hi @sarahsporck, yeah, I agree.  E2E tests pass, so theoretically the changes didn't impact the api or functionality 😂, but I think it is worth build and testing the client manually.  I'll go ahead and do that and report back, but I suggest others do that as well.  We should probably do a major version bump and release an alpha just to be on the safe side.

**Comment by sarahsporck** [comment]
Would be nice to get another review here. :)

**Comment by sarahsporck** [comment]
yep. Sadly I don't have write access and therefore cannot merge :/

**Comment by tyrauber** [comment]
@ianthetechie, would it be possible to get this reviewed and merged. It's be nice to do a major bump and release with  an alpha tag. I've got a local expo branch that builds upon this. Once this is merged and rebase and push that up for review.

**Comment by wipfli** [comment]
Yes let's grant @sarahsporck write access to this repository. We usually announce it when people get elevated access rights in the maplibre slack channel. @ianthetechie would you like to do the announcement there?

**Comment by wipfli** [comment]
Added @sarahsporck as write and elevated @ianthetechie to admin. Congrats both and thanks for your contributions!

**Comment by ianthetechie** [comment]
Done. Thanks, Oliver!

—
Ian Wagner
Stadia Maps | Founder & President
stadiamaps.com <https://stadiamaps.com/>

**Comment by ianthetechie** [comment]
Yes, this looks good to me code-wise. Feel free to merge once you're happy with this and do an alpha release with a new major version @sarahsporck :D

**Pull request merged**
