### PR TITLE
[FIX] Update fitBounds function to accept an array for padding & Fix Android Release Mode Crash

### LINKED ISSUE #295: Allow Array Type for Padding Parameter in fitBounds Function
### Steps to Trigger Behavior

1. it occurs when try to use "fitbound" function

### Link to Minimal Reproducible Example
```js
if (currentBottomSheetIndex === 0) {
        facilityCarmera?.current?.fitBounds(
          [minLon, minLat],
          [maxLon, maxLat],
          getFitBoundsArrayFacility(currentBottomSheetIndex),
          1000,
        );
      }
```

### Version(s) affected

- Development OS: macOS sonoma 14.4
- maplibre-react-native Version 9.1.0
- React Native Version 0.73.6

### PR DESCRIPTION
**Pull request by lavi02**
## Description

Fixes #295

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [X] I have run tests via `yarn test` in the root folder
- [X] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/updated a sample (`/example`)

### CODE REVIEW

**Comment by tyrauber** [comment]
@lavi02, I think [this line is good](https://github.com/maplibre/maplibre-react-native/pull/297/files#diff-ad72618eeea282299741c78248d3a8cb7197627a010159f61554f26cd0ab855eR437), we could even add null or undefined as an option since it isn't required, but I am not sure about the other changes.

I don't think we should [remove the type](https://github.com/maplibre/maplibre-react-native/pull/297/files#diff-afbc54ef2b5abd7c6523e00ac9b02f27bdcab86f4009f675ceb0525f1d5728ccL39) from documentation. This should probably be:

```
| `padding` | `Number|Number[]` | `No` | Camera padding for bound |
```
Same with [this line](https://github.com/maplibre/maplibre-react-native/pull/297/files#diff-873ce17c654718debe2fe308a2f2279bde8663686423c51f97fab2dd0722b8d9R294). 

I'd prefer specifying multiple types, rather than specifying none.

Let's also keep bounds plural. "Camera padding for bound**s**".

**Comment by lavi02** [comment]
@tyrauber  I included `animationDuration` since it also can be nullable.

**Comment by lavi02** [comment]
Can you please approve my PR? I fixed an Android release mode crash with MarkerView. This fix addresses crashes occurring in Android release mode when using MarkerView. The issue arises when updateMarkers is called while markerUpdate is still null, resulting in a NullPointerException and causing the app to crash.

@tyrauber 

```shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
       at com.mapbox.rctmgl.components.annotation.MarkerViewManager.updateMarkers(MarkerViewManager.java:20)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$4.onCameraMove(RCTMGLMapView.java:14)
       at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.executeOnCameraMove(CameraChangeDispatcher.java:30)
       at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.access$100(CameraChangeDispatcher.java)
       at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$CameraChangeHandler.handleMessage(CameraChangeDispatcher.java:32)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by tyrauber** [comment]
Thanks @lavi02, merged and in 10.0.0-alpha.6.

**Comment by caspg** [comment]
@lavi02 Why `padding` and ` animationDuration` should be nullable? Because of `null` values we have typescript errors (see the screenshot). 
I think correct types should be `number | number[] | undefined` for `padding` and `number | undefined` for `animationDuration`

```ts
fitBounds(
    northEastCoordinates: number[],
    southWestCoordinates: number[],
 
    // no `undefined` because there is default value
    padding: number | number[] = 0,

    // no `undefined` because there is default value
    animationDuration: number = 0.0,
  ): void {
```


CleanShot 2024-07-11 at 21 33 57@2x

@tyrauber CI didn't catch those Typescript errors?

**Comment by lavi02** [comment]
Yeah I just saw it yesterday, will make one more pr ASAP since debounce has type error too

**Comment by caspg** [comment]
@lavi02 I will remove that `null` from types in my branch since it's ready to be merged and it's conflicting with Camera.tsx

So you could just focus on debounce (where is that exactly?)

**Pull request merged**
